name: 'UniversalCauldron'
version: '${project.version}'
main: me.mrmango404.UniversalCauldron
api-version: '1.20'
folia-supported: true
description: A Minecraft plugin that lets you dye cauldrons with RGB colors, and use them to dye items just like Bedrock Edition.
author: oMango
commands:
  unicauldron: